/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2023-11-14 09:25:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import park.event.EventPosting;
import park.event.EventPostingDAO;

public final class Event_005fUpdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("park.event.EventPosting");
    _jspx_imports_classes.add("park.event.EventPostingDAO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("	\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("	<link rel=\"stylesheet\" href=\"./css/event.css\">\n");
      out.write("<style>\n");
      out.write("        .event_form{\n");
      out.write("            padding: 10px;\n");
      out.write("            margin: 10px;\n");
      out.write("            text-align: center;\n");
      out.write("            width: 103%;\n");
      out.write("        }\n");
      out.write("        #event_name,#event_location{\n");
      out.write("            padding: 5px;\n");
      out.write("            margin: 5px;\n");
      out.write("            width: 50%;\n");
      out.write("        }\n");
      out.write("        #event_day,#event_time{\n");
      out.write("            padding: 5px;\n");
      out.write("            margin: 5px;\n");
      out.write("            width: 30%;\n");
      out.write("        }\n");
      out.write("        #event_price,#event_age{\n");
      out.write("            padding: 5px;\n");
      out.write("            margin: 5px;\n");
      out.write("        }\n");
      out.write("        #event_explain{\n");
      out.write("            width: 80%;\n");
      out.write("            height: 200px;\n");
      out.write("        }\n");
      out.write("        .sel{\n");
      out.write("            margin: 5px;\n");
      out.write("        }\n");
      out.write("        label{\n");
      out.write("        margin: 10px;\n");
      out.write("       \n");
      out.write("        }\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	");
 
		String EventPostingValue = request.getParameter("event_number");
		int event_number = Integer.parseInt(EventPostingValue);
		
		EventPostingDAO eventPostingDAO = new EventPostingDAO();
		
		EventPosting eventPosting = eventPostingDAO.getEventInfo(event_number);
	
      out.write("\n");
      out.write("	<div class=\"diva\">\n");
      out.write("		<!-- 로고 이미지 -->\n");
      out.write("		<img src=\"./image/로고1.png\" id=\"logo\">\n");
      out.write("\n");
      out.write(" <!--로그인 버튼-->\n");
      out.write("    <div style=\"text-align: right; width: 1215px;\">\n");
      out.write("    ");

    	if(session.getAttribute("email")!=null){
    
      out.write("\n");
      out.write("	 	<button type=\"button\" onclick=\"location.href='logout.jsp'\" style=\"width:75px;\">로그아웃</button>\n");
      out.write("	 	 <h>|</h>\n");
      out.write("	    <button type=\"button\" onclick=\"location.href='mypageServlet?email=");
      out.print(session.getAttribute("email"));
      out.write("'\" style=\"width:100px;\">마이페이지</button>\n");
      out.write("	 ");

    	}else{
	 
      out.write("\n");
      out.write("		 <button type=\"button\" onclick=\"location.href='login.jsp'\" style=\"width:60px;\">로그인</button>\n");
      out.write("		 <h>|</h>\n");
      out.write("	    <button type=\"button\" onclick=\"location.href='join.jsp'\" style=\"width:100px;\">회원가입</button>\n");
      out.write("	  ");

    	}
	  
      out.write("\n");
      out.write("	    \n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("	<!-- 메뉴바 -->\n");
      out.write("	<div id=\"buttons\">\n");
      out.write("		<ul>\n");
      out.write("			<li onclick=\"location.href='review_list.jsp'\">후기</li>\n");
      out.write("			<li onclick=\"location.href='Qna_List.jsp'\">QNA</li>\n");
      out.write("			<li onclick=\"location.href='reservation_search.jsp'\">예약조회</li>\n");
      out.write("			<li onclick=\"location.href='Event_List.jsp'\">행사정보</li>\n");
      out.write("		</ul>\n");
      out.write("	</div>\n");
      out.write("    \n");
      out.write("    <!-- 가운데 가장 큰 박스 -->\n");
      out.write("	<div id=\"background\">\n");
      out.write("	\n");
      out.write("	<h3 style=\"text-align:center;\">행사글 작성 ");
      out.print(eventPosting.getEvent_number());
      out.write("</h3>\n");
      out.write("	<div id=\"whitebox\">\n");
      out.write("	\n");
      out.write("<form method=\"post\" action=\"Event_Update_success.jsp?event_number=");
      out.print(eventPosting.getEvent_number());
      out.write("\">\n");
      out.write("	<div class=\"event_form\">\n");
      out.write("	<label for=\"event_name\">행사 제목 : </label>\n");
      out.write("	\n");
      out.write("	<input type=\"text\" id=\"event_name\" name=\"event_name\" value=\"");
      out.print(eventPosting.getEvent_name() );
      out.write("\"  style=\"text-align:center;\"><br>\n");
      out.write("	\n");
      out.write("    <label for=\"event_location\">행사 장소 : </label>\n");
      out.write("    <input type=\"text\" id=\"event_location\" name=\"event_location\" value=\"");
      out.print(eventPosting.getEvent_location());
      out.write("\"  style=\"text-align:center;\"><br>\n");
      out.write("		\n");
      out.write("	<label for=\"event_day\"> 행사 기간 : </label>\n");
      out.write("	<input type=\"text\" id=\"event_day\" name=\"event_day\" value=\"");
      out.print(eventPosting.getEvent_day());
      out.write("\"  style=\"text-align:center;\">\n");
      out.write("	\n");
      out.write("	<label for=\"event_time\">행사 시간 : </label>\n");
      out.write("	<input type=\"text\" id=\"event_time\" name=\"event_time\" value=\"");
      out.print(eventPosting.getEvent_time());
      out.write("\"  style=\"text-align:center;\"><br>\n");
      out.write("	\n");
      out.write("\n");
      out.write("	\n");
      out.write("	<label for=\"event_price\">가 격 : </label>\n");
      out.write("	<input type=\"number\" id=\"event_price\" name=\"event_price\" value=\"");
      out.print(eventPosting.getEvent_price() );
      out.write("\"  style=\"text-align:center;\">\n");
      out.write("	\n");
      out.write("	<label for=\"event_age\">연 령 : </label>\n");
      out.write("	<input type=\"number\" id=\"event_age\" name=\"event_age\" value=\"");
      out.print(eventPosting.getEvent_age());
      out.write("\"  style=\"text-align:center;\"><br>\n");
      out.write("\n");
      out.write("	\n");
      out.write("	<label for=\"event_explain\">내용 : </label> <br>\n");
      out.write("	<input type=\"text\" id=\"event_explain\" name=\"event_explain\" value=\"");
      out.print(eventPosting.getEvent_explain());
      out.write("\" style=\"text-align:center\"> <br>\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	<input type=\"submit\" value=\"수정하기\" class=\"sel\">\n");
      out.write("	</div>\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("<button onclick=\"location.href='Event_List.jsp'\">돌아가기</button>\n");
      out.write("\n");
      out.write("	</div>\n");
      out.write("	</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("	");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
