/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2023-11-13 16:00:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import park.event.EventPosting;
import park.event.EventPostingDAO;

public final class Event_005fDetal_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("park.event.EventPosting");
    _jspx_imports_classes.add("park.event.EventPostingDAO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"./css/event.css\">\r\n");
      out.write("<style>\r\n");
      out.write("	.sese{\r\n");
      out.write("	margin: 30px;\r\n");
      out.write("	padding: 30px;\r\n");
      out.write("	float: left;\r\n");
      out.write("	height: 500px;\r\n");
      out.write("	}\r\n");
      out.write("	.sese2{\r\n");
      out.write("		padding: 10px;\r\n");
      out.write("		text-align: center;\r\n");
      out.write("	}\r\n");
      out.write("	.sese3{\r\n");
      out.write("		position: absolute;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        top: 50%;\r\n");
      out.write("        left: 75%; \r\n");
      out.write("        transform: translate(-50%, -50%);\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
 
		String EventPostingValue = request.getParameter("event_number");
		int event_number = Integer.parseInt(EventPostingValue);
		
		EventPostingDAO eventPostingDAO = new EventPostingDAO();
		
		EventPosting eventPosting = eventPostingDAO.getEventInfo(event_number);
	
      out.write("\r\n");
      out.write("	<div class=\"diva\">\r\n");
      out.write("		<!-- 로고 이미지 -->\r\n");
      out.write("		<img src=\"./image/로고1.png\" id=\"logo\">\r\n");
      out.write("\r\n");
      out.write(" <!--로그인 버튼-->\r\n");
      out.write("    <div style=\"text-align: right; width: 1215px;\">\r\n");
      out.write("    ");

    	if(session.getAttribute("email")!=null){
    
      out.write("\r\n");
      out.write("	 	<button type=\"button\" onclick=\"location.href='logout.jsp'\" style=\"width:75px;\">로그아웃</button>\r\n");
      out.write("	 	 <h>|</h>\r\n");
      out.write("	    <button type=\"button\" onclick=\"location.href='mypageServlet?email=");
      out.print(session.getAttribute("email"));
      out.write("'\" style=\"width:100px;\">마이페이지</button>\r\n");
      out.write("	 ");

    	}else{
	 
      out.write("\r\n");
      out.write("		 <button type=\"button\" onclick=\"location.href='login.jsp'\" style=\"width:60px;\">로그인</button>\r\n");
      out.write("		 <h>|</h>\r\n");
      out.write("	    <button type=\"button\" onclick=\"location.href='join.jsp'\" style=\"width:100px;\">회원가입</button>\r\n");
      out.write("	  ");

    	}
	  
      out.write("\r\n");
      out.write("	    \r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- 메뉴바 -->\r\n");
      out.write("	<div id=\"buttons\">\r\n");
      out.write("		<ul>\r\n");
      out.write("			<li onclick=\"location.href='review_list.jsp'\">후기</li>\r\n");
      out.write("			<li onclick=\"location.href='Qna_List.jsp'\">QNA</li>\r\n");
      out.write("			<li onclick=\"location.href='reservation_search.jsp'\">예약조회</li>\r\n");
      out.write("			<li onclick=\"location.href='Event_List.jsp'\">행사정보</li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- 가운데 가장 큰 박스 -->\r\n");
      out.write("		<div id=\"background\">\r\n");
      out.write("            <h1 class=\"as\"></h1>\r\n");
      out.write("			<img src=\"\">\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("				<div class=\"sese\">\r\n");
      out.write("					<img src=\"");
      out.print(eventPostingDAO.Image(event_number) );
      out.write("\" alt=\"event_img\" weight=\"300px\", height=\"300px\">\r\n");
      out.write("                    \r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("            <h1>");
      out.print(eventPosting.getEvent_name() );
      out.write("</h1>\r\n");
      out.write("            <br>\r\n");
      out.write("            			<div class=\"sese3\">\r\n");
      out.write("					<table class=\"sese2\">\r\n");
      out.write("						<thead>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<th class=\"jb-th-1\"> <img src=\"./image/지도아이콘.png\" style=\"width: 20px; height: 20px;\"> 장 소 :</th>\r\n");
      out.write("								<th>");
      out.print(eventPosting.getEvent_location() );
      out.write("</th>\r\n");
      out.write("							</tr>\r\n");
      out.write("						</thead>\r\n");
      out.write("						<tbody>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td> <img src=\"./image/지도아이콘.png\" style=\"width: 20px; height: 20px;\" > 행사 기간 :</td>\r\n");
      out.write("								<td>");
      out.print(eventPosting.getEvent_day() );
      out.write("</td>\r\n");
      out.write("							  </tr>\r\n");
      out.write("							  <tr>\r\n");
      out.write("								<td> <img src=\"./image/지도아이콘.png\" style=\"width: 20px; height: 20px;\" > 진행 시간 :</td>\r\n");
      out.write("								<td>");
      out.print(eventPosting.getEvent_time() );
      out.write("</td>\r\n");
      out.write("							  </tr>\r\n");
      out.write("							  <tr>\r\n");
      out.write("								<td>연 령 :</td>\r\n");
      out.write("								<td>");
      out.print(eventPosting.getEvent_age() );
      out.write("</td>\r\n");
      out.write("							  </tr>\r\n");
      out.write("							  <tr>\r\n");
      out.write("								<td>가 격 :</td>\r\n");
      out.write("								<td>");
      out.print(eventPosting.getEvent_price() );
      out.write("</td>\r\n");
      out.write("							  </tr>\r\n");
      out.write("							  <tr>\r\n");
      out.write("								<td>행사 설명 :</td>\r\n");
      out.write("								<td> ");
      out.print(eventPosting.getEvent_explain() );
      out.write("</td>\r\n");
      out.write("							  </tr>\r\n");
      out.write("						</tbody>\r\n");
      out.write("					</table>\r\n");
      out.write("				</div>\r\n");
      out.write("            </div>\r\n");
      out.write("				<input type=\"submit\" value=\"목록가기\" onclick=\"location.href='EventList.jsp'\">\r\n");
      out.write("				<input type=\"submit\" value=\"수정하기\"\r\n");
      out.write("					onclick=\"location.href='Event_Update.jsp?event_number=");
      out.print(eventPosting.getEvent_number());
      out.write("'\">\r\n");
      out.write("				<input type=\"submit\" value=\"삭제하기\"\r\n");
      out.write("					onclick=\"location.href='Event_delete_success.jsp?event_number=");
      out.print(eventPosting.getEvent_number());
      out.write("'\">\r\n");
      out.write("			</div>\r\n");
      out.write("          \r\n");
      out.write("\r\n");
      out.write("		<!-- 페이지 넘기는 버튼-->\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("			<div id=\"Pagebutton\">\r\n");
      out.write("			<button id=\"prevbutton\">이전</button>\r\n");
      out.write("\r\n");
      out.write("			<button id=\"nextbutton\">다음</button>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
