/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2023-11-14 00:23:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.PreparedStatement;
import hj.event.ReservationDTO;
import java.util.List;

public final class mypage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("hj.event.ReservationDTO");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("<title>GO, FESTIVAL 마이페이지</title>\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"./hjCss/mypage.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"./hjCss/recancelButton.css\">\n");
      out.write("\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("    <!-- 이미지 로고 -->\n");
      out.write("   <img src=\"./image/로고1.png\" id=\"logo\">\n");
      out.write("   \n");
      out.write("    \n");
      out.write("    <!--로그인 버튼-->\n");
      out.write("    <div style=\"text-align: right; width: 1215px;\">\n");
      out.write("    ");

    	if(session.getAttribute("email")!=null){
    
      out.write("\n");
      out.write("	 	<button type=\"button\" onclick=\"location.href='logout.jsp'\" style=\"width:75px;\">로그아웃</button>\n");
      out.write("	 	 <h>|</h>\n");
      out.write("	    <button type=\"button\" onclick=\"location.href='mypageServlet?email=");
      out.print(session.getAttribute("email"));
      out.write("'\" style=\"width:100px;\">마이페이지</button>\n");
      out.write("  \n");
      out.write("	 ");

    	}else{
	 
      out.write("\n");
      out.write("		 <button type=\"button\" onclick=\"location.href='login.jsp'\" style=\"width:60px;\">로그인</button>\n");
      out.write("		 <h>|</h>\n");
      out.write("	    <button type=\"button\" onclick=\"location.href='join.jsp'\" style=\"width:100px;\">회원가입</button>\n");
      out.write("	  ");

    	}
	  
      out.write("\n");
      out.write("\n");
      out.write("<!-- 메뉴바 -->\n");
      out.write("  <div id=\"buttons\">\n");
      out.write("		<ul>\n");
      out.write("			<li onclick=\"location.href='review_list.jsp'\">후기</li>\n");
      out.write("			<li onclick=\"location.href='Qna_List.jsp'\">QNA</li>\n");
      out.write("			<li onclick=\"location.href='reservation_search.jsp'\">예약조회</li>\n");
      out.write("			<li onclick=\"location.href='Event_List.jsp'\">행사정보</li>\n");
      out.write("		</ul>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("     <div id=\"background\">\n");
      out.write("     <h3 style=\"text-align:center;padding-top:20px;\">마이페이지</h3>\n");
      out.write("	     <div id=\"reviewbox\">\n");
      out.write("	     <!-- 내 정보가 표시될 공간 -->\n");
      out.write("	    \n");
      out.write("		     <div>\n");
      out.write("		     	");

					String email = (String) session.getAttribute("email");
					String name = (String) session.getAttribute("name");	
					String phonenumber = (String) session.getAttribute("phonenumber");
				
      out.write("\n");
      out.write("				\n");
      out.write("				<p> 이메일: ");
      out.print(email );
      out.write("</p>\n");
      out.write("				<p> 이름: ");
      out.print(name );
      out.write("</p>\n");
      out.write("				<p> 전화번호: ");
      out.print(phonenumber );
      out.write("</p>\n");
      out.write("		     </div>\n");
      out.write("		     <!-- 예약목록 -->\n");
      out.write("		     <div id =\"reservationList\">\n");
      out.write("		     <h2>예약 목록</h2>\n");
      out.write("				<table border=\"1\">\n");
      out.write("				<tr>\n");
      out.write("					<th>예약번호</th>\n");
      out.write("					<th>이메일</th>\n");
      out.write("					<th>연락처</th>\n");
      out.write("					<th>인원</th>\n");
      out.write("					<th>행사명</th>\n");
      out.write("					<th>위치</th>\n");
      out.write("					<th>총액</th>\n");
      out.write("				</tr>\n");
      out.write("				");

			    List<ReservationDTO> rdto = (List<ReservationDTO>) request.getAttribute("rdto");
			
			    for(ReservationDTO reservation : rdto){
			
      out.write("\n");
      out.write("			<tr>\n");
      out.write("			    <td>");
      out.print(reservation.getId());
      out.write("</td>\n");
      out.write("			    <td>");
      out.print(reservation.getEmail());
      out.write("</td>\n");
      out.write("			    <td>");
      out.print(reservation.getPhonenumber());
      out.write("</td>\n");
      out.write("			    <td>");
      out.print(reservation.getPerson());
      out.write("</td>\n");
      out.write("			    <td>");
      out.print(reservation.getEvent_name());
      out.write("</td>\n");
      out.write("			    <td>");
      out.print(reservation.getEvent_location());
      out.write("</td>\n");
      out.write("			    <td>");
      out.print(reservation.getTotal());
      out.write("</td>\n");
      out.write("			</tr>\n");
      out.write("			");

			    }
			
      out.write("\n");
      out.write("			</table>\n");
      out.write("		     </div>\n");
      out.write("			<div id=\"recancelButton\">\n");
      out.write("				<form action=\"mypage_update.jsp\" method=\"post\" style=\"display: inline-block;\">\n");
      out.write("					<input type=\"hidden\" name=\"email\" value=\"");
      out.print(email);
      out.write("\">\n");
      out.write("					<input type=\"submit\" value=\"내 정보 수정\">				\n");
      out.write("				</form>\n");
      out.write("				<form action=\"\" method=\"post\" style=\"display: inline-block;\">\n");
      out.write("					<input type=\"submit\" value=\"회원탈퇴\">\n");
      out.write("				</form>\n");
      out.write("			</div>\n");
      out.write("	     \n");
      out.write("	      </div>  \n");
      out.write("      </div> \n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
