/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2023-11-17 03:31:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import park.event.EventPosting;
import park.event.EventPostingDAO;

public final class Event_005fDetal_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("park.event.EventPosting");
    _jspx_imports_classes.add("park.event.EventPostingDAO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"./css/event.css\">\n");
      out.write("<style>\n");
      out.write(".postingName {\n");
      out.write("	margin: -30px 0px 35px 0px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("table, td, th, tbody, thead {\n");
      out.write("	border-collapse: collapse;\n");
      out.write("	border: none;\n");
      out.write("	width: 500px;\n");
      out.write("	margin: auto;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".postingImg {\n");
      out.write("	width: 400px;\n");
      out.write("	height: 300px;\n");
      out.write("	padding: 62px;\n");
      out.write("	float: left;\n");
      out.write("}\n");
      out.write("\n");
      out.write("td, th {\n");
      out.write("    text-align: left;\n");
      out.write("    padding: 15px;\n");
      out.write("    font-size: 18px;\n");
      out.write("    margin: 0px 0px 0px 0px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".sese3 {\n");
      out.write("	margin: 0px 173px 0px 0px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".reserButton {\n");
      out.write("    float: left;\n");
      out.write("    border: none;\n");
      out.write("    background-color: moccasin;\n");
      out.write("    width: 140px;\n");
      out.write("    height: 40px;\n");
      out.write("    text-align: center;\n");
      out.write("        margin: 0px -4px 8px 29px;\n");
      out.write("}\n");
      out.write(".reserButton2{\n");
      out.write("    float: left;\n");
      out.write("    border: none;\n");
      out.write("    background-color: moccasin;\n");
      out.write("    width: 140px;\n");
      out.write("    height: 40px;\n");
      out.write("    text-align: center;\n");
      out.write("    margin: 0px -4px 8px 86px\n");
      out.write("}\n");
      out.write(".reserButton3{\n");
      out.write("    float: left;\n");
      out.write("    border: none;\n");
      out.write("    background-color: moccasin;\n");
      out.write("    width: 140px;\n");
      out.write("    height: 40px;\n");
      out.write("    text-align: center;\n");
      out.write("    margin: -60px -25px 22px 88px;\n");
      out.write("}\n");
      out.write(".pagExplain{\n");
      out.write("\n");
      out.write("}\n");
      out.write(" details{margin-bottom:10px;}\n");
      out.write("  details summary{    padding: 0 10px;\n");
      out.write("    background: antiquewhite;\n");
      out.write("    color: darkgray;\n");
      out.write("    height: 35px;\n");
      out.write("    line-height: 35px;\n");
      out.write("    font-weight: bold;\n");
      out.write("    cursor: pointer;\n");
      out.write("    width: 97%;\n");
      out.write("    text-align: center;}\n");
      out.write("    details div{\n");
      out.write("    text-align: center;\n");
      out.write("    }\n");
      out.write("    .buttontype{\n");
      out.write("    margin: 20px 0px 0px 0px;\n");
      out.write("    }\n");
      out.write("    .buttonLeft{\n");
      out.write("    float: left;\n");
      out.write("    }\n");
      out.write("    .test{\n");
      out.write("    margin-top: -80px;\n");
      out.write("    }\n");
      out.write("    .diva{\n");
      out.write("        margin-bottom: 182px;\n");
      out.write("    }\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("	<div class=\"diva\">\n");
      out.write("		<!-- 로고 이미지 -->\n");
      out.write("		<img src=\"./image/로고1.png\" id=\"logo\" onclick=\"location.href='home.jsp'\">\n");
      out.write("\n");
      out.write("		<!--로그인 버튼-->\n");
      out.write("	 <div style=\"text-align: right; width: 1215px;\">\n");
      out.write("    ");

    if(session.getAttribute("email")!=null){
    
      out.write("\n");
      out.write("	 	<button type=\"button\" onclick=\"location.href='logout.jsp'\" style=\"background:none;border:none;width:75px;\">로그아웃</button>\n");
      out.write("	 	 <h>|</h>\n");
      out.write("	    <button type=\"button\" onclick=\"location.href='mypageServlet?email=");
      out.print(session.getAttribute("email"));
      out.write("'\" style=\"background:none;border:none;width:100px;\">마이페이지</button>\n");
      out.write("	 ");

	 }else{
	 
      out.write("\n");
      out.write("		 <button type=\"button\" onclick=\"location.href='login.jsp'\" style=\"background:none;border:none;width:60px;\">로그인</button>\n");
      out.write("		 <h>|</h>\n");
      out.write("	    <button type=\"button\" onclick=\"location.href='join.jsp'\" style=\"background:none;border:none;width:100px;\">회원가입</button>\n");
      out.write("	  ");

	  }
	  
      out.write("\n");
      out.write("			\n");
      out.write("			\n");
      out.write("\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("		<!-- 메뉴바 -->\n");
      out.write("		<div id=\"buttons\">\n");
      out.write("			<ul>\n");
      out.write("				<li onclick=\"location.href='review_list.jsp'\">후기</li>\n");
      out.write("				<li onclick=\"location.href='Qna_List.jsp'\">QNA</li>\n");
      out.write("				<li onclick=\"location.href='reservation_search.jsp'\">예약조회</li>\n");
      out.write("				<li onclick=\"location.href='Event_List.jsp'\">행사정보</li>\n");
      out.write("			</ul>\n");
      out.write("		</div>\n");
      out.write("	");

	String EventPostingValue = request.getParameter("event_number");
	int event_number = Integer.parseInt(EventPostingValue);

	EventPostingDAO eventPostingDAO = new EventPostingDAO();

	EventPosting eventPosting = eventPostingDAO.getEventInfo(event_number);
	
      out.write("\n");
      out.write("\n");
      out.write("		<!-- 가운데 가장 큰 박스 -->\n");
      out.write("		<div id=\"background\">\n");
      out.write("			<h1 class=\"as\"></h1>\n");
      out.write("\n");
      out.write("			<div class=\"sese\">\n");
      out.write("				<img src=\"");
      out.print(eventPostingDAO.Image(event_number));
      out.write("\" alt=\"event_img\"\n");
      out.write("					class=\"postingImg\">\n");
      out.write("\n");
      out.write("\n");
      out.write("			</div>\n");
      out.write("			<h1 class=\"postingName\">");
      out.print(eventPosting.getEvent_name());
      out.write("</h1>\n");
      out.write("			<br>\n");
      out.write("			<div class=\"sese3\">\n");
      out.write("				<table class=\"sese2\">\n");
      out.write("					<thead>\n");
      out.write("						<tr>\n");
      out.write("							<th class=\"jb-th-1\"><img src=\"./image/지도아이콘.png\"\n");
      out.write("								style=\"width: 20px; height: 20px;\"> 장 소 :</th>\n");
      out.write("							<th>");
      out.print(eventPosting.getEvent_location());
      out.write("</th>\n");
      out.write("						</tr>\n");
      out.write("					</thead>\n");
      out.write("					<tbody>\n");
      out.write("						<tr>\n");
      out.write("							<td><img src=\"./image/달력.png\"\n");
      out.write("								style=\"width: 20px; height: 20px;\"> 행사 기간 :</td>\n");
      out.write("							<td>");
      out.print(eventPosting.getEvent_day());
      out.write("</td>\n");
      out.write("						</tr>\n");
      out.write("						<tr>\n");
      out.write("							<td><img src=\"./image/시계.png\"\n");
      out.write("								style=\"width: 20px; height: 20px;\"> 진행 시간 :</td>\n");
      out.write("							<td>");
      out.print(eventPosting.getEvent_time());
      out.write("</td>\n");
      out.write("						</tr>\n");
      out.write("						<tr>\n");
      out.write("							<td>연 령 :</td>\n");
      out.write("							<td>");
      out.print(eventPosting.getEvent_age());
      out.write("세 이상</td>\n");
      out.write("						</tr>\n");
      out.write("						<tr>\n");
      out.write("							<td>가 격 :</td>\n");
      out.write("							<td>");
      out.print(eventPosting.getEvent_price());
      out.write("원</td>\n");
      out.write("						</tr>\n");
      out.write("\n");
      out.write("					</tbody>\n");
      out.write("				</table>\n");
      out.write("				<div class=\"buttontype\">\n");
      out.write("				<div class=\"buttonLeft\">\n");
      out.write("				<div>\n");
      out.write("					<input type=\"button\" class=\"reserButton\" value=\"예약하기\" onclick=\"location.href='reservation.jsp?event_number=");
      out.print(eventPosting.getEvent_number());
      out.write("'\">\n");
      out.write("					\n");
      out.write("									    <input type=\"submit\" class=\"reserButton\" value=\"후기보기\" onclick=\"location.href='review_searchlist.jsp?event_number=");
      out.print(eventPosting.getEvent_number());
      out.write("'\">\n");
      out.write("									    \n");
      out.write("				    <input type=\"submit\" class=\"reserButton\" value=\"후기 작성하기\" onclick=\"location.href='review_write.jsp?event_number=");
      out.print(eventPosting.getEvent_number());
      out.write("'\">\n");
      out.write("				    \n");
      out.write("				    </div>\n");
      out.write("				    <div>\n");
      out.write("				    <input type=\"submit\" class=\"reserButton2\" value=\"문의하기\" onclick=\"location.href='Qna_Write2.jsp?event_number=");
      out.print(eventPosting.getEvent_number());
      out.write("'\">\n");
      out.write("					\n");
      out.write("					<input type=\"submit\" class=\"reserButton2\" value=\"목록가기\"  onclick=\"location.href='Event_List.jsp'\"> \n");
      out.write("					</div>\n");
      out.write("					</div>\n");
      out.write("				\n");
      out.write("\n");
      out.write("			</div>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("	<!-- 페이지 넘기는 버튼-->\n");
      out.write("\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("<details class=\"pagExplain\">\n");
      out.write("    <summary>자세히 보기</summary>\n");
      out.write("    <div>\n");
      out.write("	");
      out.print(eventPosting.getEvent_explain() );
      out.write("\n");
      out.write("    </div>\n");
      out.write("   \n");
      out.write("    \n");
      out.write("</details>\n");
      out.write("			<div class=\"test\">\n");
      out.write("	");

					if (session.getAttribute("email").equals("kiga1234@kiga1234")) {
					
      out.write("\n");
      out.write("					<input type=\"submit\" value=\"수정하기\" class=\"reserButton3\" onclick=\"location.href='Event_Update.jsp?event_number=");
      out.print(eventPosting.getEvent_number());
      out.write("'\">\n");
      out.write("			\n");
      out.write("					<input type=\"submit\" value=\"삭제하기\" class=\"reserButton3\" onclick=\"location.href='Event_delete_success.jsp?event_number=");
      out.print(eventPosting.getEvent_number());
      out.write("'\">\n");
      out.write("				");
} 
      out.write("\n");
      out.write("				</div>\n");
      out.write("				</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
