/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2023-11-16 10:25:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import gaeul.review.festivalDTO;
import gaeul.review.selectDAO;
import gaeul.review.deleteDAO;
import java.util.*;

public final class review_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("gaeul.review.selectDAO");
    _jspx_imports_classes.add("gaeul.review.festivalDTO");
    _jspx_imports_classes.add("gaeul.review.deleteDAO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("    \n");
      out.write("     \n");
      out.write("     \n");
      out.write("     \n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<title>GO, festival 후기게시판</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"review.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("	<!-- 로고 이미지 -->\n");
      out.write("	<img src=\"./image/로고1.png\" id=\"logo\" onclick=\"location.href='home.jsp'\">\n");
      out.write("\n");
      out.write("\n");
      out.write("	 <div style=\"text-align: right; width: 1215px;\">\n");
      out.write("    ");

    if(session.getAttribute("email")!=null){
    
      out.write("\n");
      out.write("	 	<button type=\"button\" onclick=\"location.href='logout.jsp'\" style=\"background:none;border:none;width:75px;\">로그아웃</button>\n");
      out.write("	 	 <h>|</h>\n");
      out.write("	    <button type=\"button\" onclick=\"location.href='mypageServlet?email=");
      out.print(session.getAttribute("email"));
      out.write("'\" style=\"background:none;border:none;width:100px;\">마이페이지</button>\n");
      out.write("	 ");

	 }else{
	 
      out.write("\n");
      out.write("		 <button type=\"button\" onclick=\"location.href='login.jsp'\" style=\"background:none;border:none;width:60px;\">로그인</button>\n");
      out.write("		 <h>|</h>\n");
      out.write("	    <button type=\"button\" onclick=\"location.href='join.jsp'\" style=\"background:none;border:none;width:100px;\">회원가입</button>\n");
      out.write("	  ");

	  }
	  
      out.write("\n");
      out.write("	    \n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("	<div id=\"buttons\">\n");
      out.write("	<!--로그인 버튼-->\n");
      out.write("   <ul style=\"list-style:none;\">\n");
      out.write("			<li style=\"float:left;margin-left:170px;\" onclick=\"location.href='Event_List.jsp'\">행사정보</li>\n");
      out.write("		    <li style=\"float:left;margin-left:170px;\" onclick=\"location.href='reservation_search.jsp'\">예약조회</li>\n");
      out.write("		    <li style=\"float:left;margin-left:170px;\" onclick=\"location.href='Qna_List.jsp'\">QNA</li>\n");
      out.write("			<li style=\"float:left;margin-left:170px;\" onclick=\"location.href='review_list.jsp'\">후기</li>\n");
      out.write("		</ul>\n");
      out.write("	</div>\n");
      out.write("		\n");
      out.write("	\n");
      out.write("	 	 <div id=\"background\"  >\n");
      out.write("	 	 \n");
      out.write("	 	 <!-- 축제 정보 검색하기 -->\n");
      out.write("	 	 \n");
      out.write("	 	 \n");
      out.write("	 	 <div id=\"searchbox\" style=\"margin-left:90px;margin-top:10px;\">\n");
      out.write("	 	 \n");
      out.write("	 	 	<select class=\"form-select\" name=\"searchField\" style=\"height:25px;border-radius:5px;\">\n");
      out.write("								<option value=\"0\">선택</option>\n");
      out.write("								<option value=\"review_title\">[1]해달축제</option>\n");
      out.write("								<option value=\"review_title\">[2]뭔헨 필하모익~클라스~강</option>\n");
      out.write("								<option value=\"review_title\">[3]임영웅의 콘서트</option>\n");
      out.write("								<option value=\"review_title\">[4]이무진의 전국투어 콘서트</option>\n");
      out.write("								<option value=\"review_title\">[5]벤허</option>\n");
      out.write("								<option value=\"review_title\">[6]렌트</option>\n");
      out.write("								\n");
      out.write("						</select>\n");
      out.write("						\n");
      out.write("						<!-- 리스트 검색창 -->\n");
      out.write("						<form method=\"post\" action=\"review_searchlist.jsp\">\n");
      out.write("							<input type=\"text\" name=\"event_number\" style=\"margin-top:10px;border-radius:5px;border:2px solid gray;width:400px;height:25px;\" placeholder=\"검색할 축제번호를 입력해주세요 !\"> \n");
      out.write("							\n");
      out.write("							<!-- 검색버튼 -->\n");
      out.write("							<input type=\"submit\" value=\"검색\" style=\"width:80px;height:30px;border-radius:5px;border:2px solid gray;\">\n");
      out.write("						</form>\n");
      out.write("		 	 \n");
      out.write(" 	 	</div>\n");
      out.write(" 	 	\n");
      out.write(" 	 	<div id=\"reviewbox\" style=\"margin-bottom:50px;\">\n");
      out.write(" 	 	<div id=\"reviewlist\" >\n");
      out.write("            <table id=\"list\" >\n");
      out.write("            \n");
      out.write("                <tr style=\"font-size:15px; height:30px;\">\n");
      out.write("                <!-- 열 내용 -->\n");
      out.write("			       <th style=\"width:70px;background-color:rgb(223, 223, 224);\">행사</th>\n");
      out.write("			        <th style=\"width:70px;background-color:rgb(223, 223, 224);\">리뷰 제목</th>\n");
      out.write("			       <th style=\"width:50px;background-color:rgb(223, 223, 224);\">리뷰 작성일</th>\n");
      out.write("                </tr>\n");
      out.write("        \n");
      out.write("        ");

                selectDAO fDAO = new selectDAO();
			        ArrayList<festivalDTO> list =fDAO.List();
			       
			        for(festivalDTO f: list){
			       	String content=f.getReview();
			       	String title=f.getReview_title();
			       	Date date=f.getReviewdate();
			       	String eventname=f.getEvent_name();
                
      out.write("\n");
      out.write("                \n");
      out.write("                <!-- 행 내용 -->\n");
      out.write("        		<tr style=\"font-size:13px;background:white; \" >\n");
      out.write("        		<td style=\"padding:5px;;\">");
      out.print( eventname);
      out.write("</td>\n");
      out.write("                <td style=\"width:300px\"><a href=\"choose_result.jsp?review_number=");
      out.print(f.getReviewnumber());
      out.write('"');
      out.write('>');
      out.print(title);
      out.write("</a></td>\n");
      out.write("                <td>");
      out.print(date);
      out.write("</td>\n");
      out.write("            \n");
      out.write("            </tr>\n");
      out.write("        ");

        } 
        
        
      out.write("\n");
      out.write("            </table>\n");
      out.write("             </div>\n");
      out.write("           </div>\n");
      out.write("        </div>\n");
      out.write(" 	\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
